### ISSUE TITLE
Extend "Style and Content Guide" and add a "Contribution" section

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-org#1]
```[tasklist]
### Tasks
- [ ] Add what should be documented and what rather not
- [ ] Add a section about the desired "Voice" of the documentation
- [ ] Add a list of different article / page types and what to use in which cases
- [ ] TBD
```

**Comment by ralf401** [comment]
Content more or less in place already. Working on #63 and try to consider the idea of this issue.
