### ISSUE TITLE
Add postponed parts and implement feedback

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-org#15]
```[tasklist]
### Tasks
- [x] Firewall config
- [x] SELinux config
- [x] Elasticsearch example configuration/installation
- [x] Connect Zammad with ES
- [x] Docker env vars
- [x] ~Elasticsearch Troubleshooting~ (see #17) & Indexed Attributes
- [x] Backup & Restore
- [x] First Steps
- [x] Webserver Configuration
- [x] Cleanup / rework already added content based on feedback
- [x] ~Migrate to PostgreSQL~ => skipped because new installations are PostgreSQL only and new doc doesn't need to cover that
- [x] Convert code style from `` to `
- [x] Docker env vars in code style; default values as badges
```
