### ISSUE TITLE
Migrate postponed content from system docs

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-org#17]
```[tasklist]
### Tasks
- [x] Backup/Restore troubleshooting and database helper script
- [x] Migrate Zammad to another host
- [x] Elasticsearch Troubleshooting (only 1 scenario)
```

**Comment by ralf401** [comment]
Hi @YetAnotherGerrit, 

I would love to hear your opinion on this. Are the mentioned parts still needed? Should we keep all? 

1. [Backup/restore troubleshooting](https://docs.zammad.org/en/latest/appendix/backup-and-restore/troubleshooting.html): Now that I read it again, this could be useful for some... but not sure.
2. [Database helper script](https://docs.zammad.org/en/latest/appendix/backup-and-restore/little-helpers.html): there is just one described.
3. [Migrate Zammad to a new host](https://docs.zammad.org/en/latest/appendix/backup-and-restore/migrate-hosts.html): at least the part in the tab "Full filesystem dump" is a mess.
4. [Elasticsearch Troubleshooting](https://docs.zammad.org/en/latest/install/elasticsearch/troubleshooting.html): there is just one problem mentioned about missing data.

I'm open for each direction. But at least parts of the mentioned content is not in a good shape in my opinion.

**Comment by YetAnotherGerrit** [comment]
I used 1. and 2. several times this year as a consultant. Regarding 3./4. I don't know if this has helped users in the past.

Do you have access to visitors' statistics from our webserver-logs?

**Comment by ralf401** [comment]
Yes but only the last 30 days:

- 33.435 page views in total
- Package installation no. 1 visited page with 4.108 visits
- Elasticsearch troubleshooting with 82 visits
- Migrate to a new host with 260 visits

I guess it would be good to migrate it then, perhaps tweaking it more or less... Let's see what I can do.
