### ISSUE TITLE
Create a glossary

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-org#20]
See https://github.com/zammad/coordination-ui-ux/issues/23#issuecomment-2535946826

```[tasklist]
### Tasks
- [x] Navigation
- [x] Navigation Tab
- [x] Second Level Navigation
- [x] (Content)Sidebar
- [x] Sidebar Tab (trigger)
- [x] Active Sidebar Tab
- [x] (Side) Panels
- [x] Dialogs
- [x] Release notes
```
